### ISSUE TITLE
Deal with missing offenses

### ISSUE THREAD

**Issue by DSharm** [christi-liongson/covid_decarceration#14]
Using information in sentence component file and minimum sentence length, get "most serious offense code" at the ID and commitment prefix level to bring into our final dataset. 

See https://github.com/christi-liongson/covid_decarceration/issues/8 for more details

**Comment by crunes** [comment]
Created a CSV that filters sentence component by minimum sentence length and maximum sentence length to proxy for the missing most serious offense values.
