### ISSUE TITLE
NC data feature engineering, traintest split, preprocess

### ISSUE THREAD

**Issue by DSharm** [christi-liongson/covid_decarceration#21]
We now have a most complete dataset constructed in build_dataset, and our holdout dataset (active_sentences). Both can be found on google drive.

The purpose of this ticket and associated notebook (features_split_preprocess) is to carry out the following:
- explore features we already have and create new ones
- once that is done, carry out an appropriate train/test/validate split - taking temporal validation into account
- pre processing (impute missingness separately for train/test/validate, normalize, etc)

The end goal of features_split_preprocess is to have our final datasets ready for analysis. The code should then be moved into our .py files so the notebook and intermediate datasets can eventually be deleted

**Comment by crunes** [comment]
Pushed my pipeline.py file, but will likely need to edit/add functions.

**Comment by DSharm** [comment]
Awesome thanks! Where is the file saved / which branch? I couldn't see it, possibly missing something obvious

**Comment by crunes** [comment]
Ah no, it was a quirk of my laptop - the push never went through but it should be up now.
