### ISSUE TITLE
Understand how sqlite works and turn inmate profile into db

### ISSUE THREAD

**Issue by DSharm** [christi-liongson/covid_decarceration#4]

**Comment by DSharm** [comment]
This should be helpful https://www.sqlitetutorial.net/sqlite-python/

**Comment by DSharm** [comment]
Created branch to work on this issue: create_ncdoc_db

**Comment by DSharm** [comment]
I took a crack at getting us started. Basically watched the sqlite tutorial and created some files (create_db, config, and main) to create a new ncdoc database and initialize an empty Inmates file. 

Definitely not tied to this workflow, so let me know what you think!

Next steps on this issue ticket I believe:
- inserting data into the inmates table
- dealing with data types (i think all will be added as text - see my note in main.py)

**Comment by crunes** [comment]
I updated the main.py file to default all columns to string (without it, I ran into this error: "DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False"). This message didn't come up when I added the parameter (dtype=str) to the pd.read_csv() function.

**Comment by DSharm** [comment]
Good call! Gonna go ahead and close this ticket
