### ISSUE TITLE
Push all tables into SQL lite database 

### ISSUE THREAD

**Issue by DSharm** [christi-liongson/covid_decarceration#5]

**Comment by crunes** [comment]
Tested the updated main.py file to push all tables to the database. Ran into a few bumps:
- My laptop has been having memory/space issues in general, but specifically came across this error: "database or disk is full"
- Unrecognized token "#" in table "INMT9CF1.csv"

**Comment by crunes** [comment]
Computer crashed (lack of application storage) while uploading the tables to the database but it looks like our database now has the following tables:
- APPT7AA1
- INMT4AA1
- INMT4BB1
- OFNT1BA1
- OFNT3AA1
- test

Next steps: 
- Upload the remaining 7 tables / delete the test table
- Run a few test queries to make sure the data are in there
- Write a script to clean / reformat data types

**Comment by DSharm** [comment]
Update:
- Database has all 12 tables now with data successfully pushed.
- Deleted test tables
-I ran a couple test queries as well and they work. Created a query_db.py file to play with queries - this should probably be its own milestone / branch so I can write more on that elsewhere
- Unrecognized token "#" in table "INMT9CF1.csv" was resolved by removing "#" character from column names
- Unfortunately the final .db file is over 5 gigs and too large to keep on git. I'm uploading it to google_drive folder - since the data is in there and working i dont see us having to recreate that file often, but we can communicate if we have recreated + uploaded so each person can make sure to have an updated copy

Gonna go ahead and close this issue ticket!

**Comment by christi-liongson** [comment]
Hi @DSharm  - I ran into the large file issue with a previous project. I  was able to get around this with Git LFS (https://git-lfs.github.com/).  Happy to help with setting this up or show you what I did! Would be really neat if others can access this database and benefit from your hard work :D

**Comment by DSharm** [comment]
Oh @christi-liongson that's awesome, thank you for the tip! I'll look into Git LFS and let you know if I run into issues. Thanks so much - definitely wasn't thrilled about the Gdrive solution

**Comment by DSharm** [comment]
@christi-liongson - how big was the file you uploaded? i installed git lfs but am getting the following error:

![Screen Shot 2020-05-13 at 1 29 14 PM](https://user-images.githubusercontent.com/15899459/81850536-bf0b4b00-951d-11ea-880d-de90c7eae1b8.png)
